# Generated by Django 5.0.7 on 2024-10-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mask_detector", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maskimage",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
